name: CI/CD for Spring Boot with Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build Spring Boot Application
        run: ./gradlew build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2  # 기본 리전 설정

      - name: Log in to AWS ECR (ap-northeast-2)
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY_2 }}

      - name: Log in to AWS ECR (ap-northeast-1)
        run: |
          aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY_1 }}

      - name: Build and Push Docker Image to AWS ECR (Both Regions)
        run: |
          IMAGE_NAME_2=${{ secrets.AWS_ECR_REGISTRY_2 }}/ecr_repo_seoul
          IMAGE_NAME_1=${{ secrets.AWS_ECR_REGISTRY_1 }}/ecr_repo_tokyo
          VERSION=$(date +%Y%m%d%H%M%S)

          # Docker 이미지 빌드
          docker build -t $IMAGE_NAME_2:latest -t $IMAGE_NAME_2:$VERSION .

          # ap-northeast-1 용으로 태그 변경
          docker tag $IMAGE_NAME_2:latest $IMAGE_NAME_1:latest
          docker tag $IMAGE_NAME_2:$VERSION $IMAGE_NAME_1:$VERSION

          # ap-northeast-2 푸시
          docker push $IMAGE_NAME_2:latest
          docker push $IMAGE_NAME_2:$VERSION

          # ap-northeast-1 푸시
          docker push $IMAGE_NAME_1:latest
          docker push $IMAGE_NAME_1:$VERSION
